services:
  db:
    image: postgres:16.10-alpine
    container_name: librarytest-db
    environment:
      POSTGRES_DB: biblioteca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d biblioteca"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: librarytest-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/biblioteca
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL: "true"
      SERVER_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  pgdata: